### ISSUE TITLE
EquivalentClasses with DataHasValue

### ISSUE THREAD

**Issue by rwynne** [liveontologies/elk-reasoner#61]
Attached is a simple Java class along with two small ontologies (rename extensions as needed).  Each ontology has two classes that are "clones" with differing IRIs (fragments 392656009 and Copy-392656009).

Reasoning the file with DataHasValue axioms, the two classes are not returned as equivalent.
Reasoning the file without DataHasValue axioms, the two classes are equivalent.

For my use case, I have been creating RxNorm classes within the SNOMED ontology and then report areas where clinical drugs do not align.  As you can imagine, it is still extremely valuable to get these class equivalencies for free.  Now that these value axioms have moved away from using numbers represented as classes, is this still possible?

Note: If I view both ontologies in Protege (version 5.5.0-beta-7) and run ELK, the equivalence sign is visible in the hierarchy!

[TestELK.txt](https://github.com/liveontologies/elk-reasoner/files/6980405/TestELK.txt)
[with-datahasvalue.txt](https://github.com/liveontologies/elk-reasoner/files/6980408/with-datahasvalue.txt)
[without-datahasvalue.txt](https://github.com/liveontologies/elk-reasoner/files/6980409/without-datahasvalue.txt)

**Comment by ykazakov** [comment]
Thanks for the detailed report! Which version of ELK did you use? 
In general ELK is not guaranteed to derive equivalences of identical classes that contain unsupported features (and DataHasValue is not fully supported). However, version 0.4.3 indeed derived equivalences for DataHasValue because they were represented by identical internal objects. Any reason why you cannot use this version from OWL API?

In the latest development version 0.5.0-SNAPSHOT this behaviour has changed due to changes in the internal representation, so identical classes in your example are not detected as equivalent. I can take a look if the old behaviour can be restored.

I would appreciate if you use small examples in your report. Most of the content of the attached files are not relevant for the issue.

**Comment by rwynne** [comment]
@ykazakov Any updates if this behavior can be restored?

In the case of SNOMED, I wrote a workaround to back-convert the concrete domain values to owl classes and add their former predicates. This was simpler than downgrading to OA4 and 0.4.3.

**Comment by ykazakov** [comment]
@rwynne sorry, I did not have much time to work on ELK yet.

**Comment by rwynne** [comment]
@ykazakov Any updates to this issue? A fix may also benefit Protege issue https://github.com/protegeproject/protege/issues/910 . Thanks!

**Comment by balhoff** [comment]
Hi @ykazakov I found this issue as I just came to report this behavior change as well. In my case I was relying on ELK 0.4.3 finding `A` and `B` equivalent in this ontology:

```
Ontology(
Declaration(Class(<http://example.org/A>))
Declaration(Class(<http://example.org/B>))
Declaration(Class(<http://example.org/C>))
Declaration(ObjectProperty(<http://example.org/r>))
EquivalentClasses(<http://example.org/A> ObjectComplementOf(ObjectSomeValuesFrom(<http://example.org/r> <http://example.org/C>)))
EquivalentClasses(<http://example.org/B> ObjectComplementOf(ObjectSomeValuesFrom(<http://example.org/r> <http://example.org/C>)))
)
```

These structural equivalences can be very useful in coercing ELK to materialize certain unsupported inferences.
